### ISSUE TITLE
getting 'Not Found' from raw.githubusercontent.com urls, even with the correct netrc auth

### ISSUE THREAD

**Issue by olivoil** [componentjs/remotes.js#19]
I'm getting a lot of "Not Found" responses from github on raw.githubusercontent.com urls for private repositories.

Cogent does use the credentials from netrc correctly though, and I have the correct accesses to the repo.

Any idea where it could be coming from?

**Comment by nazim848** [comment]
Anyone who is getting the same error can try this solution: https://www.debugpoint.com/failed-connect-raw-githubusercontent-com-port-443/

It resolved for me :)

**Comment by nitingujjar88** [comment]
Golden key

**Comment by nitingujjar88** [comment]
Golden key

**Comment by genobear** [comment]
I had this issue because I set an Authorisation header in my browser for API testing. In case anyone else has similar issue
