### ISSUE TITLE
.netrc credentials is not working, right?

### ISSUE THREAD

**Issue by cristiandouce** [componentjs/remotes.js#24]
I've been running into issue while `component install` using private repositories.

I have my `.netrc` configured, but it fails constantly saying no remote found for repository `my/private@version`.

After doing:

```bash
export GITHUB_USER=cristiandouce
export GITHUB_PASSWORD=mypassword
component install
```
> Same credentials as `~/.netrc` file.

It installs all my dependencies without any failing!

It seems to be missing at this section: 
```js
  // set the github API auth via environment
  // otherwise, use netrc or something.
  if (!options.auth && GITHUB_USERNAME && GITHUB_PASSWORD)
    options.auth = GITHUB_USERNAME + ':' + GITHUB_PASSWORD
```

> https://github.com/componentjs/remotes.js/blob/master/lib/remotes/github.js#L22-L23

I've been tracking this down from `componentjs/resolver.js` down from the install script.

**Comment by netpoetica** [comment]
This is definitely something I need to write a test for :-) which version of component are you using? Also, this may be a silly question, but in your .netrc, did you use a [personal token](https://github.com/settings/applications#personalaccess-tokens) or possibly accidentally/maybe just put in your password?

There is an example [here](https://github.com/componentjs/guide/blob/master/component/getting-started.md#configuring-github-access), make sure to set `password x-oauth-basic` as well.

I will try to test remotes w/ my .netrc tonight and come up with a test as well, thanks for reporting. Let me know if either of those simple fixes do the trick

**Comment by cristiandouce** [comment]
@netpoetica I'm using latest release of component.

Also yeah, I'm using the oauth token :dancer: 

Yet, could you point me in code where is the .netrc loaded for a `component install` execution?

Thanks! :grinning:

**Comment by timaschew** [comment]
component-resolver using cogent, actually it's a fork (with a fix) of cogent: https://github.com/timaschew/cogent/tree/fix-redirects
And cogent is using the `netrc` npm module

**Comment by cristiandouce** [comment]
Well, somehow it's not loading for me from the netrc.

**Comment by timaschew** [comment]
yep, that's true, you need to define two hosts for github: 
`api.github.com` AND `raw.githubusercontent.com`

I updated the readme: https://github.com/componentjs/guide/blob/master/component/getting-started.md#configuring-github-access

**Comment by cristiandouce** [comment]
cool! :dancer: thanks!

**Comment by netpoetica** [comment]
@timaschew I don't recall, come to think of it, ever seeing the .netrc working, but I was under the impression that the .netrc file was used internally by CURL. If you check out [this post](https://confluence.atlassian.com/display/STASH/Permanently+authenticating+with+Git+repositories#PermanentlyauthenticatingwithGitrepositories-Usingthe.netrcfile) from BitBucket it talks about how Git uses CURL, which should use your .netrc.

However, peeking around the web it looks like any other package managers are doing some manual parsing, so this assumption (and that BitBucket article), must be incorrect.

**Comment by timaschew** [comment]
Yes this is strange, maybe curl is an optional dependency? So if curl is installed or was avaiable during installation or dependes on the configuration of git, it really use curl.
this is from http://git-scm.com/book/eo/v1/Ekkomenci-Installing-Git

> To install Git, you need to have the following libraries that Git depends on: curl, zlib, openssl, expat, and libiconv.

But this is definite not true, because I have installed git in a VM and curl is not available.
